### ISSUE TITLE
Contract Activation

### ISSUE THREAD

**Issue by majacque** [YounitedCredit/younitedpay-sdk-php#10]
Hi,
in the ClientApiService class, there isn't an activateContract() function.
But I see a Model 'ActivateContract', a Request 'ActivateContractRequest', and a Response 'ActivateContractResponse'.
Why choose not to implement the function?

**Comment by kgleizes** [comment]
Hello @majacque 

Thank you for this issue.

The service was written to help developers to use the differents classes, but this request (ActivateContract) 
was not implemented as you saw well.

Anyway, you can easily use it as mentionned in the documentation [here](https://github.com/YounitedCredit/younitedpay-sdk-php#activate-contract) : 

```php
use YounitedPaySDK\Client;
use YounitedPaySDK\Request\ActivateContractRequest;
use YounitedPaySDK\Model\ActivateContract;

$clientId = 'your-client-id';
$clientSecret = 'your-secret-idtoken';

$body = (new ActivateContract())
    ->setContractReference('contract-ref');

$request = (new ActivateContractRequest())
    ->setModel($body)
    ->enableSandbox();
```

We will discuss with my team to add it as soon as possible.

Thank you for opening this issue, feel free to open it again if you have more questions.
