### ISSUE TITLE
Contract Activation Webhook

### ISSUE THREAD

**Issue by majacque** [YounitedCredit/younitedpay-sdk-php#11]
Hi,
why in the Model 'MerchantUrls', there isn't the 'onActivateWebhookUrl'?

**Comment by kgleizes** [comment]
Hi @majacque 

This webhook did not exist at the time the SDK was make for the CMS using it (PrestaShop, Magento2 for example).

When it was added on the API, decision was taken to let merchants update their stores for these important legal points
and to not add this functionnality on the SDK part.

If you need it you can easily make your own class 'MerchantUrlsCustom' that extends this one and implements
the onActivateWebhookUrl to use it later.

Then here in the [initialization of the contract](https://github.com/YounitedCredit/younitedpay-sdk-php#initialize-a-contract) you could do something such as : 

```php
$merchantUrls = (new MerchantUrlsCustom())
    ->setOnApplicationFailedRedirectUrl('on-application-failed-redirect-url.com')
    ->setOnApplicationSucceededRedirectUrl('on-application-succeeded-redirect-url.com')
    ->setOnActivatedWebhookUrl('on-activated-webhook-url.com') // added in custom class MerchantUrlsCustom
    ->setOnCanceledWebhookUrl('on-canceled-webhook-url.com')
    ->setOnWithdrawnWebhookUrl('on-withdrawn-webhook-url.com');
```

Please note that this is a legal point for merchants to activate contracts only if the order is shipped, and responsability
is on their side if they did it whereas it was not the case.

Feel free to open again this issue if you have more questions.

Thank you.
